E:\项目\个人博客开发\backend\.venv\Lib\site-packages\shortuuidfield\__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  VERSION = __import__('pkg_resources') \
E:\项目\个人博客开发\backend\.venv\Lib\site-packages\shortuuidfield\__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  VERSION = __import__('pkg_resources') \
--- Logging error ---
Traceback (most recent call last):
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\utils\deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/articles/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\context.py", line 88, in __getitem__
    raise KeyError(key)
KeyError: 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 897, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 914, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [exception_notes] in [{'True': True, 'False': False, 'None': None}, {'is_email': False, 'unicode_hint': '', 'frames': [{'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x000001917DD27140>, 'type': 'django', 'filename': 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\django\\core\\handlers\\exception.py', 'function': 'inner', 'lineno': 55, 'vars': [('request', "<WSGIRequest: POST '/api/articles'>"), ('exc', 'RuntimeError("You called this URL via POST, but the URL doesn\'t end in a slash and you have APPEND_SLASH set. Django can\'t redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/articles/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.")'), ('get_response', '<CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>')], 'id': 1724392829248, 'pre_context': ['', '        return inner', '    else:', '', '        @wraps(get_response)', '        def inner(request):', '            try:'], 'context_line': '                response = get_response(request)', 'post_context': ['            except Exception as exc:', '                response = response_for_exception(request, exc)', '            return response', '', '        return inner', ''], 'pre_context_lineno': 48, 'colno': '\n                               ^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n               ^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x000001917DD24D00>, 'type': 'django', 'filename': 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\django\\utils\\deprecation.py', 'function': '__call__', 'lineno': 122, 'vars': [('self', '<CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>'), ('request', "<WSGIRequest: POST '/api/articles'>"), ('response', '<HttpResponseNotFound status_code=404, "text/html; charset=utf-8">')], 'id': 1724392819968, 'pre_context': ['        if self.async_mode:', '            return self.__acall__(request)', '        response = None', '        if hasattr(self, "process_request"):', '            response = self.process_request(request)', '        response = response or self.get_response(request)', '        if hasattr(self, "process_response"):'], 'context_line': '            response = self.process_response(request, response)', 'post_context': ['        return response', '', '    async def __acall__(self, request):', '        """', '        Async version of __call__ that is swapped in when an async request', '        is running.'], 'pre_context_lineno': 115, 'colno': '\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x000001917DD24B80>, 'type': 'django', 'filename': 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\django\\middleware\\common.py', 'function': 'process_response', 'lineno': 108, 'vars': [('self', '<CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>'), ('request', "<WSGIRequest: POST '/api/articles'>"), ('response', '<HttpResponseNotFound status_code=404, "text/html; charset=utf-8">')], 'id': 1724392819584, 'pre_context': ['        """', '        When the status code of the response is 404, it may redirect to a path', '        with an appended slash if should_redirect_with_slash() returns True.', '        """', '        # If the given URL is "Not Found", then check if we should redirect to', '        # a path with a slash appended.', '        if response.status_code == 404 and self.should_redirect_with_slash(request):'], 'context_line': '            return self.response_redirect_class(self.get_full_path_with_slash(request))', 'post_context': ['', '        # Add the Content-Length header to non-streaming responses if not', '        # already set.', '        if not response.streaming and not response.has_header("Content-Length"):', '            response.headers["Content-Length"] = str(len(response.content))', ''], 'pre_context_lineno': 101, 'colno': '\n                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x000001917DD26640>, 'type': 'django', 'filename': 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\django\\middleware\\common.py', 'function': 'get_full_path_with_slash', 'lineno': 87, 'vars': [('self', '<CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>'), ('request', "<WSGIRequest: POST '/api/articles'>"), ('new_path', "'/api/articles/'")], 'id': 1724392826432, 'pre_context': ['        Raise a RuntimeError if settings.DEBUG is True and request.method is', '        DELETE, POST, PUT, or PATCH.', '        """', '        new_path = request.get_full_path(force_append_slash=True)', '        # Prevent construction of scheme relative urls.', '        new_path = escape_leading_slashes(new_path)', '        if settings.DEBUG and request.method in ("DELETE", "POST", "PUT", "PATCH"):'], 'context_line': '            raise RuntimeError(', 'post_context': ['                "You called this URL via %(method)s, but the URL doesn\'t end "', '                "in a slash and you have APPEND_SLASH set. Django can\'t "', '                "redirect to the slash URL while maintaining %(method)s data. "', '                "Change your form to point to %(url)s (note the trailing "', '                "slash), or set APPEND_SLASH=False in your Django settings."', '                % {'], 'pre_context_lineno': 80, 'colno': '\n                ^', 'tb_area_colno': '\n    ^'}], 'request': <WSGIRequest: POST '/api/articles'>, 'request_meta': {'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPCODE_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\appcode.vmoptions', 'APPDATA': 'C:\\Users\\Administrator\\AppData\\Roaming', 'CLION_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\clion.vmoptions', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'LZD-20250429OYI', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DATAGRIP_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\datagrip.vmoptions', 'DATASPELL_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\dataspell.vmoptions', 'DEVECOSTUDIO_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\devecostudio.vmoptions', 'DJANGO_SETTINGS_MODULE': 'BlogSystem.settings', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'EFC_48844_1592913036': '1', 'EFC_48844_2283032206': '1', 'ELECTRON_MIRROR': 'https://cdn.npm.taobao.org/dist/electron/', 'GATEWAY_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\gateway.vmoptions', 'GOLAND_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\goland.vmoptions', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\Administrator', 'IDEA_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\idea.vmoptions', 'JETBRAINSCLIENT_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\jetbrainsclient.vmoptions', 'JETBRAINS_CLIENT_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\jetbrains_client.vmoptions', 'LOCALAPPDATA': 'C:\\Users\\Administrator\\AppData\\Local', 'LOGONSERVER': '\\\\LZD-20250429OYI', 'NODE_HOME': 'D:\\Software\\nodejs', 'NUMBER_OF_PROCESSORS': '20', 'ONEDRIVE': 'C:\\Users\\Administrator\\OneDrive', 'ONEDRIVECONSUMER': 'C:\\Users\\Administrator\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;D:\\Software\\Git\\cmd;D:\\Software\\nodejs\\;D:\\Software\\nodejs;D:\\Software\\nodejs\\node_global;D:\\Software\\nodejs\\node_cache;D:\\Software\\anaconda3;D:\\Software\\anaconda3\\Scripts;D:\\Software\\anaconda3\\Library\\bin;D:\\Software\\anaconda3\\Library\\mingw-w64\\bin;C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR;C:\\Program Files\\dotnet\\;C:\\Program Files\\Pandoc\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;D:\\Software\\Xshell\\;D:\\Software\\Xftp\\;C:\\Program Files\\Calibre2\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;D:\\Software\\Redis-x64-5.0.14.1;C:\\Users\\Administrator\\scoop\\shims;C:\\Users\\Administrator\\AppData\\Local\\pnpm;C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\;C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python313\\;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;D:\\Software\\nodejs\\node_global;D:\\Software\\Microsoft VS Code\\bin;D:\\Software\\Project Graph;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Administrator\\AppData\\Local\\Programs\\superfile\\;', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PHPSTORM_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\phpstorm.vmoptions', 'PNPM_HOME': 'C:\\Users\\Administrator\\AppData\\Local\\pnpm', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 154 Stepping 3, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '9a03', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PROJECT_DIR': 'E:\\项目\\个人博客开发\\backend\\BlogSystem\\', 'PROMPT': '$P$G', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYCHARM_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\pycharm.vmoptions', 'REDIS_EXE': 'D:\\Software\\Redis-x64-5.0.14.1\\redis-server.exe', 'RIDER_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\rider.vmoptions', 'RUBYMINE_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\rubymine.vmoptions', 'RUN_MAIN': 'true', 'SESSIONNAME': 'Console', 'STUDIO_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\studio.vmoptions', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp', 'TRILIUM_DATA_DIR': 'E:\\trilium_data', 'USERDOMAIN': 'LZD-20250429OYI', 'USERDOMAIN_ROAMINGPROFILE': 'LZD-20250429OYI', 'USERNAME': 'Administrator', 'USERPROFILE': 'C:\\Users\\Administrator', 'VENV_PYTHON': 'E:\\项目\\个人博客开发\\backend\\.venv\\Scripts\\python.exe', 'WEBIDE_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\webide.vmoptions', 'WEBSTORM_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\webstorm.vmoptions', 'WINDIR': 'C:\\WINDOWS', 'ZES_ENABLE_SYSMAN': '1', 'SERVER_NAME': 'LZD-20250429OYI', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '8000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '0', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'POST', 'PATH_INFO': '/api/articles', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_AUTHORIZATION': '********************', 'HTTP_USER_AGENT': 'Apifox/1.0.0 (https://apifox.com)', 'HTTP_ACCEPT': '*/*', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x000001917DD15D80>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='gbk'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>}, 'request_COOKIES_items': dict_items([]), 'user_str': 'AnonymousUser', 'filtered_POST_items': [], 'settings': {'ABSOLUTE_URL_OVERRIDES': {}, 'ADMINS': [], 'ALLOWED_HOSTS': [], 'APPEND_SLASH': True, 'AUTHENTICATION_BACKENDS': '********************', 'AUTH_PASSWORD_VALIDATORS': '********************', 'AUTH_USER_MODEL': '********************', 'BASE_DIR': WindowsPath('E:/项目/个人博客开发/backend/BlogSystem'), 'CACHES': {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}, 'CACHE_EXPIRY_HOURS': 1, 'CACHE_MIDDLEWARE_ALIAS': 'default', 'CACHE_MIDDLEWARE_KEY_PREFIX': '********************', 'CACHE_MIDDLEWARE_SECONDS': 600, 'CELERY_BEAT_SCHEDULE': {'reset-weather-quota': {'task': 'informa.tasks.reset_monthly_quota', 'schedule': <crontab: 0 0 1 * * (m/h/dM/MY/d)>}, 'update-weather-cache': {'task': 'informa.tasks.update_weather_caches', 'schedule': <crontab: */30 * * * * (m/h/dM/MY/d)>}, 'clean-deleted-media': {'task': 'informa.management.commands.clean_deleted_media.Command.handle', 'schedule': <crontab: 0 0 1 * * (m/h/dM/MY/d)>}}, 'CELERY_BROKER_URL': 'redis://localhost:6379/0', 'CELERY_RESULT_BACKEND': 'redis://localhost:6379/0', 'CELERY_TIMEZONE': 'Asia/Shanghai', 'CORS_ALLOWED_ORIGINS': ['http://localhost:5173'], 'CORS_ALLOW_CREDENTIALS': True, 'CORS_ALLOW_HEADERS': ['authorization', 'content-type'], 'CORS_ALLOW_METHODS': ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'], 'CSRF_COOKIE_AGE': 31449600, 'CSRF_COOKIE_DOMAIN': None, 'CSRF_COOKIE_HTTPONLY': False, 'CSRF_COOKIE_NAME': 'csrftoken', 'CSRF_COOKIE_PATH': '/', 'CSRF_COOKIE_SAMESITE': 'Lax', 'CSRF_COOKIE_SECURE': False, 'CSRF_FAILURE_VIEW': 'django.views.csrf.csrf_failure', 'CSRF_HEADER_NAME': 'HTTP_X_CSRFTOKEN', 'CSRF_TRUSTED_ORIGINS': [], 'CSRF_USE_SESSIONS': False, 'DATABASES': {'default': {'ENGINE': 'django.db.backends.postgresql', 'NAME': 'blogsystem', 'USER': 'postgres', 'PASSWORD': '********************', 'HOST': '127.0.0.1', 'PORT': '5432', 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'CONN_HEALTH_CHECKS': False, 'OPTIONS': {}, 'TIME_ZONE': None, 'TEST': {'CHARSET': None, 'COLLATION': None, 'MIGRATE': True, 'MIRROR': None, 'NAME': None}}}, 'DATABASE_ROUTERS': [], 'DATA_UPLOAD_MAX_MEMORY_SIZE': 2621440, 'DATA_UPLOAD_MAX_NUMBER_FIELDS': 1000, 'DATA_UPLOAD_MAX_NUMBER_FILES': 100, 'DATETIME_FORMAT': 'N j, Y, P', 'DATETIME_INPUT_FORMATS': ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M'], 'DATE_FORMAT': 'N j, Y', 'DATE_INPUT_FORMATS': ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y'], 'DEBUG': True, 'DEBUG_PROPAGATE_EXCEPTIONS': False, 'DECIMAL_SEPARATOR': '.', 'DEFAULT_AUTO_FIELD': 'django.db.models.BigAutoField', 'DEFAULT_CHARSET': 'utf-8', 'DEFAULT_EXCEPTION_REPORTER': 'django.views.debug.ExceptionReporter', 'DEFAULT_EXCEPTION_REPORTER_FILTER': 'django.views.debug.SafeExceptionReporterFilter', 'DEFAULT_FROM_EMAIL': 'webmaster@localhost', 'DEFAULT_INDEX_TABLESPACE': '', 'DEFAULT_TABLESPACE': '', 'DISALLOWED_USER_AGENTS': [], 'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend', 'EMAIL_HOST': 'localhost', 'EMAIL_HOST_PASSWORD': '********************', 'EMAIL_HOST_USER': '', 'EMAIL_PORT': 25, 'EMAIL_SSL_CERTFILE': None, 'EMAIL_SSL_KEYFILE': '********************', 'EMAIL_SUBJECT_PREFIX': '[Django] ', 'EMAIL_TIMEOUT': None, 'EMAIL_USE_LOCALTIME': False, 'EMAIL_USE_SSL': False, 'EMAIL_USE_TLS': False, 'FILE_UPLOAD_DIRECTORY_PERMISSIONS': None, 'FILE_UPLOAD_HANDLERS': ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler'], 'FILE_UPLOAD_MAX_MEMORY_SIZE': 2621440, 'FILE_UPLOAD_PERMISSIONS': 420, 'FILE_UPLOAD_TEMP_DIR': None, 'FIRST_DAY_OF_WEEK': 0, 'FIXTURE_DIRS': [], 'FORCE_SCRIPT_NAME': None, 'FORMAT_MODULE_PATH': None, 'FORMS_URLFIELD_ASSUME_HTTPS': False, 'FORM_RENDERER': 'django.forms.renderers.DjangoTemplates', 'IGNORABLE_404_URLS': [], 'INSTALLED_APPS': ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'rest_framework_simplejwt', 'corsheaders', 'rest_framework', 'django_filters', 'acticles', 'system', 'informa'], 'INTERNAL_IPS': [], 'LANGUAGES': [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokm\xe5l'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], 'LANGUAGES_BIDI': ['he', 'ar', 'ar-dz', 'ckb', 'fa', 'ug', 'ur'], 'LANGUAGE_CODE': 'zh-hans', 'LANGUAGE_COOKIE_AGE': None, 'LANGUAGE_COOKIE_DOMAIN': None, 'LANGUAGE_COOKIE_HTTPONLY': False, 'LANGUAGE_COOKIE_NAME': 'django_language', 'LANGUAGE_COOKIE_PATH': '/', 'LANGUAGE_COOKIE_SAMESITE': None, 'LANGUAGE_COOKIE_SECURE': False, 'LOCALE_PATHS': [], 'LOGGING': {'version': 1, 'disable_existing_loggers': False, 'handlers': {'file': {'level': 'DEBUG', 'class': 'logging.FileHandler', 'filename': 'E:\\项目\\个人博客开发\\backend\\BlogSystem\\debug.log'}}, 'loggers': {'django': {'handlers': ['file'], 'level': 'DEBUG', 'propagate': True}, 'celery': {'handlers': ['file'], 'level': 'DEBUG', 'propagate': True}}}, 'LOGGING_CONFIG': 'logging.config.dictConfig', 'LOGIN_REDIRECT_URL': '/accounts/profile/', 'LOGIN_URL': '/accounts/login/', 'LOGOUT_REDIRECT_URL': None, 'MANAGERS': [], 'MEDIA_ROOT': 'E:\\项目\\个人博客开发\\backend\\BlogSystem\\media', 'MEDIA_URL': '/media/', 'MESSAGE_STORAGE': 'django.contrib.messages.storage.fallback.FallbackStorage', 'MIDDLEWARE': ['corsheaders.middleware.CorsMiddleware', 'django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware'], 'MIGRATION_MODULES': {}, 'MONITORED_LOCATIONS': ['Beijing', 'Shanghai', 'New York', 'WuHan'], 'MONTH_DAY_FORMAT': 'F j', 'NUMBER_GROUPING': 0, 'PASSWORD_HASHERS': '********************', 'PASSWORD_RESET_TIMEOUT': '********************', 'PREPEND_WWW': False, 'REST_FRAMEWORK': {'DEFAULT_AUTHENTICATION_CLASSES': '********************', 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',)}, 'ROOT_URLCONF': 'BlogSystem.urls', 'SECRET_KEY': '********************', 'SECRET_KEY_FALLBACKS': '********************', 'SECURE_CONTENT_TYPE_NOSNIFF': True, 'SECURE_CROSS_ORIGIN_OPENER_POLICY': 'same-origin', 'SECURE_HSTS_INCLUDE_SUBDOMAINS': False, 'SECURE_HSTS_PRELOAD': False, 'SECURE_HSTS_SECONDS': 0, 'SECURE_PROXY_SSL_HEADER': None, 'SECURE_REDIRECT_EXEMPT': [], 'SECURE_REFERRER_POLICY': 'same-origin', 'SECURE_SSL_HOST': None, 'SECURE_SSL_REDIRECT': False, 'SERVER_EMAIL': 'root@localhost', 'SESSION_CACHE_ALIAS': 'default', 'SESSION_COOKIE_AGE': 1209600, 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_NAME': 'sessionid', 'SESSION_COOKIE_PATH': '/', 'SESSION_COOKIE_SAMESITE': 'Lax', 'SESSION_COOKIE_SECURE': False, 'SESSION_ENGINE': 'django.contrib.sessions.backends.db', 'SESSION_EXPIRE_AT_BROWSER_CLOSE': False, 'SESSION_FILE_PATH': None, 'SESSION_SAVE_EVERY_REQUEST': False, 'SESSION_SERIALIZER': 'django.contrib.sessions.serializers.JSONSerializer', 'SETTINGS_MODULE': 'BlogSystem.settings', 'SHORT_DATETIME_FORMAT': 'm/d/Y P', 'SHORT_DATE_FORMAT': 'm/d/Y', 'SIGNING_BACKEND': 'django.core.signing.TimestampSigner', 'SILENCED_SYSTEM_CHECKS': [], 'SIMPLE_JWT': {'ACCESS_TOKEN_LIFETIME': '********************', 'REFRESH_TOKEN_LIFETIME': '********************', 'ROTATE_REFRESH_TOKENS': '********************', 'BLACKLIST_AFTER_ROTATION': True, 'UPDATE_LAST_LOGIN': True, 'ALGORITHM': 'HS256', 'SIGNING_KEY': '********************', 'VERIFYING_KEY': '********************', 'AUDIENCE': None, 'ISSUER': None, 'AUTH_HEADER_TYPES': '********************', 'USER_ID_FIELD': 'id', 'USER_ID_CLAIM': 'user_id', 'USER_AUTHENTICATION_RULE': '********************', 'AUTH_TOKEN_CLASSES': '********************', 'TOKEN_TYPE_CLAIM': '********************'}, 'STATICFILES_DIRS': [], 'STATICFILES_FINDERS': ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder'], 'STATIC_ROOT': None, 'STATIC_URL': '/static/', 'STORAGES': {'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'}, 'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'}}, 'TEMPLATES': [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}], 'TEST_NON_SERIALIZED_APPS': [], 'TEST_RUNNER': 'django.test.runner.DiscoverRunner', 'THOUSAND_SEPARATOR': ',', 'TIME_FORMAT': 'P', 'TIME_INPUT_FORMATS': ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M'], 'TIME_ZONE': 'UTC', 'USE_I18N': True, 'USE_THOUSAND_SEPARATOR': False, 'USE_TZ': True, 'USE_X_FORWARDED_HOST': False, 'USE_X_FORWARDED_PORT': False, 'WEATHER_API_HOST': '********************', 'WEATHER_API_KEY': '********************', 'WEATHER_API_URL': '********************', 'WSGI_APPLICATION': 'BlogSystem.wsgi.application', 'X_FRAME_OPTIONS': 'DENY', 'YEAR_MONTH_FORMAT': 'F Y'}, 'sys_executable': 'E:\\项目\\个人博客开发\\backend\\.venv\\Scripts\\python.exe', 'sys_version_info': '3.12.7', 'server_time': datetime.datetime(2025, 7, 17, 8, 31, 46, 383427, tzinfo=datetime.timezone.utc), 'django_version_info': '5.2.4', 'sys_path': ['E:\\项目\\个人博客开发\\backend\\BlogSystem', 'E:\\项目\\个人博客开发\\backend\\BlogSystem', 'D:\\Software\\anaconda3\\python312.zip', 'D:\\Software\\anaconda3\\DLLs', 'D:\\Software\\anaconda3\\Lib', 'D:\\Software\\anaconda3', 'E:\\项目\\个人博客开发\\backend\\.venv', 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages', 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\setuptools\\_vendor'], 'template_info': None, 'template_does_not_exist': False, 'postmortem': None, 'request_GET_items': <generator object MultiValueDict.items at 0x000001917DD35150>, 'request_FILES_items': <generator object MultiValueDict.items at 0x000001917DD37780>, 'request_insecure_uri': 'http://127.0.0.1:8000/api/articles', 'raising_view_name': '', 'exception_type': 'RuntimeError', 'exception_value': "You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/articles/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.", 'lastframe': {'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x000001917DD26640>, 'type': 'django', 'filename': 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\django\\middleware\\common.py', 'function': 'get_full_path_with_slash', 'lineno': 87, 'vars': [('self', '<CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>'), ('request', "<WSGIRequest: POST '/api/articles'>"), ('new_path', "'/api/articles/'")], 'id': 1724392826432, 'pre_context': ['        Raise a RuntimeError if settings.DEBUG is True and request.method is', '        DELETE, POST, PUT, or PATCH.', '        """', '        new_path = request.get_full_path(force_append_slash=True)', '        # Prevent construction of scheme relative urls.', '        new_path = escape_leading_slashes(new_path)', '        if settings.DEBUG and request.method in ("DELETE", "POST", "PUT", "PATCH"):'], 'context_line': '            raise RuntimeError(', 'post_context': ['                "You called this URL via %(method)s, but the URL doesn\'t end "', '                "in a slash and you have APPEND_SLASH set. Django can\'t "', '                "redirect to the slash URL while maintaining %(method)s data. "', '                "Change your form to point to %(url)s (note the trailing "', '                "slash), or set APPEND_SLASH=False in your Django settings."', '                % {'], 'pre_context_lineno': 80, 'colno': '\n                ^', 'tb_area_colno': '\n    ^'}}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\anaconda3\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\xe5' in position 20788: illegal multibyte sequence
Call stack:
  File "D:\Software\anaconda3\Lib\threading.py", line 1032, in _bootstrap
    self._bootstrap_inner()
  File "D:\Software\anaconda3\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "D:\Software\anaconda3\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Software\anaconda3\Lib\socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\Software\anaconda3\Lib\socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Software\anaconda3\Lib\socketserver.py", line 761, in __init__
    self.handle()
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\servers\basehttp.py", line 230, in handle
    self.handle_one_request()
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\servers\basehttp.py", line 253, in handle_one_request
    handler.run(self.server.get_app())
  File "D:\Software\anaconda3\Lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\contrib\staticfiles\handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\corsheaders\middleware.py", line 56, in __call__
    result = self.get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\views\debug.py", line 429, in get_traceback_html
    return t.render(c)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 320, in render
    match = condition.eval(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 941, in _resolve_lookup
    logger.debug(
Message: "Exception while resolving variable '%s' in template '%s'."
Arguments: ('exception_notes', 'unknown')
--- Logging error ---
Traceback (most recent call last):
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\utils\deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/articles/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\context.py", line 88, in __getitem__
    raise KeyError(key)
KeyError: 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 897, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 914, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [exception_notes] in [{'True': True, 'False': False, 'None': None}, {'is_email': False, 'unicode_hint': '', 'frames': [{'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x000001917DD27140>, 'type': 'django', 'filename': 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\django\\core\\handlers\\exception.py', 'function': 'inner', 'lineno': 55, 'vars': [('request', "<WSGIRequest: POST '/api/articles'>"), ('exc', 'RuntimeError("You called this URL via POST, but the URL doesn\'t end in a slash and you have APPEND_SLASH set. Django can\'t redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/articles/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.")'), ('get_response', '<CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>')], 'id': 1724392829248, 'pre_context': ['', '        return inner', '    else:', '', '        @wraps(get_response)', '        def inner(request):', '            try:'], 'context_line': '                response = get_response(request)', 'post_context': ['            except Exception as exc:', '                response = response_for_exception(request, exc)', '            return response', '', '        return inner', ''], 'pre_context_lineno': 48, 'colno': '\n                               ^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n               ^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x000001917DD24D00>, 'type': 'django', 'filename': 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\django\\utils\\deprecation.py', 'function': '__call__', 'lineno': 122, 'vars': [('self', '<CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>'), ('request', "<WSGIRequest: POST '/api/articles'>"), ('response', '<HttpResponseNotFound status_code=404, "text/html; charset=utf-8">')], 'id': 1724392819968, 'pre_context': ['        if self.async_mode:', '            return self.__acall__(request)', '        response = None', '        if hasattr(self, "process_request"):', '            response = self.process_request(request)', '        response = response or self.get_response(request)', '        if hasattr(self, "process_response"):'], 'context_line': '            response = self.process_response(request, response)', 'post_context': ['        return response', '', '    async def __acall__(self, request):', '        """', '        Async version of __call__ that is swapped in when an async request', '        is running.'], 'pre_context_lineno': 115, 'colno': '\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x000001917DD24B80>, 'type': 'django', 'filename': 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\django\\middleware\\common.py', 'function': 'process_response', 'lineno': 108, 'vars': [('self', '<CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>'), ('request', "<WSGIRequest: POST '/api/articles'>"), ('response', '<HttpResponseNotFound status_code=404, "text/html; charset=utf-8">')], 'id': 1724392819584, 'pre_context': ['        """', '        When the status code of the response is 404, it may redirect to a path', '        with an appended slash if should_redirect_with_slash() returns True.', '        """', '        # If the given URL is "Not Found", then check if we should redirect to', '        # a path with a slash appended.', '        if response.status_code == 404 and self.should_redirect_with_slash(request):'], 'context_line': '            return self.response_redirect_class(self.get_full_path_with_slash(request))', 'post_context': ['', '        # Add the Content-Length header to non-streaming responses if not', '        # already set.', '        if not response.streaming and not response.has_header("Content-Length"):', '            response.headers["Content-Length"] = str(len(response.content))', ''], 'pre_context_lineno': 101, 'colno': '\n                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x000001917DD26640>, 'type': 'django', 'filename': 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\django\\middleware\\common.py', 'function': 'get_full_path_with_slash', 'lineno': 87, 'vars': [('self', '<CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>'), ('request', "<WSGIRequest: POST '/api/articles'>"), ('new_path', "'/api/articles/'")], 'id': 1724392826432, 'pre_context': ['        Raise a RuntimeError if settings.DEBUG is True and request.method is', '        DELETE, POST, PUT, or PATCH.', '        """', '        new_path = request.get_full_path(force_append_slash=True)', '        # Prevent construction of scheme relative urls.', '        new_path = escape_leading_slashes(new_path)', '        if settings.DEBUG and request.method in ("DELETE", "POST", "PUT", "PATCH"):'], 'context_line': '            raise RuntimeError(', 'post_context': ['                "You called this URL via %(method)s, but the URL doesn\'t end "', '                "in a slash and you have APPEND_SLASH set. Django can\'t "', '                "redirect to the slash URL while maintaining %(method)s data. "', '                "Change your form to point to %(url)s (note the trailing "', '                "slash), or set APPEND_SLASH=False in your Django settings."', '                % {'], 'pre_context_lineno': 80, 'colno': '\n                ^', 'tb_area_colno': '\n    ^'}], 'request': <WSGIRequest: POST '/api/articles'>, 'request_meta': {'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPCODE_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\appcode.vmoptions', 'APPDATA': 'C:\\Users\\Administrator\\AppData\\Roaming', 'CLION_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\clion.vmoptions', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'LZD-20250429OYI', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DATAGRIP_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\datagrip.vmoptions', 'DATASPELL_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\dataspell.vmoptions', 'DEVECOSTUDIO_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\devecostudio.vmoptions', 'DJANGO_SETTINGS_MODULE': 'BlogSystem.settings', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'EFC_48844_1592913036': '1', 'EFC_48844_2283032206': '1', 'ELECTRON_MIRROR': 'https://cdn.npm.taobao.org/dist/electron/', 'GATEWAY_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\gateway.vmoptions', 'GOLAND_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\goland.vmoptions', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\Administrator', 'IDEA_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\idea.vmoptions', 'JETBRAINSCLIENT_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\jetbrainsclient.vmoptions', 'JETBRAINS_CLIENT_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\jetbrains_client.vmoptions', 'LOCALAPPDATA': 'C:\\Users\\Administrator\\AppData\\Local', 'LOGONSERVER': '\\\\LZD-20250429OYI', 'NODE_HOME': 'D:\\Software\\nodejs', 'NUMBER_OF_PROCESSORS': '20', 'ONEDRIVE': 'C:\\Users\\Administrator\\OneDrive', 'ONEDRIVECONSUMER': 'C:\\Users\\Administrator\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;D:\\Software\\Git\\cmd;D:\\Software\\nodejs\\;D:\\Software\\nodejs;D:\\Software\\nodejs\\node_global;D:\\Software\\nodejs\\node_cache;D:\\Software\\anaconda3;D:\\Software\\anaconda3\\Scripts;D:\\Software\\anaconda3\\Library\\bin;D:\\Software\\anaconda3\\Library\\mingw-w64\\bin;C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR;C:\\Program Files\\dotnet\\;C:\\Program Files\\Pandoc\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;D:\\Software\\Xshell\\;D:\\Software\\Xftp\\;C:\\Program Files\\Calibre2\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;D:\\Software\\Redis-x64-5.0.14.1;C:\\Users\\Administrator\\scoop\\shims;C:\\Users\\Administrator\\AppData\\Local\\pnpm;C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\;C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python313\\;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;D:\\Software\\nodejs\\node_global;D:\\Software\\Microsoft VS Code\\bin;D:\\Software\\Project Graph;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Administrator\\AppData\\Local\\Programs\\superfile\\;', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PHPSTORM_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\phpstorm.vmoptions', 'PNPM_HOME': 'C:\\Users\\Administrator\\AppData\\Local\\pnpm', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 154 Stepping 3, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '9a03', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PROJECT_DIR': 'E:\\项目\\个人博客开发\\backend\\BlogSystem\\', 'PROMPT': '$P$G', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYCHARM_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\pycharm.vmoptions', 'REDIS_EXE': 'D:\\Software\\Redis-x64-5.0.14.1\\redis-server.exe', 'RIDER_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\rider.vmoptions', 'RUBYMINE_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\rubymine.vmoptions', 'RUN_MAIN': 'true', 'SESSIONNAME': 'Console', 'STUDIO_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\studio.vmoptions', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp', 'TRILIUM_DATA_DIR': 'E:\\trilium_data', 'USERDOMAIN': 'LZD-20250429OYI', 'USERDOMAIN_ROAMINGPROFILE': 'LZD-20250429OYI', 'USERNAME': 'Administrator', 'USERPROFILE': 'C:\\Users\\Administrator', 'VENV_PYTHON': 'E:\\项目\\个人博客开发\\backend\\.venv\\Scripts\\python.exe', 'WEBIDE_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\webide.vmoptions', 'WEBSTORM_VM_OPTIONS': 'D:\\Software\\PyCharm 2024.3.3\\Win\\jetbra\\vmoptions\\webstorm.vmoptions', 'WINDIR': 'C:\\WINDOWS', 'ZES_ENABLE_SYSMAN': '1', 'SERVER_NAME': 'LZD-20250429OYI', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '8000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '0', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'POST', 'PATH_INFO': '/api/articles', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_AUTHORIZATION': '********************', 'HTTP_USER_AGENT': 'Apifox/1.0.0 (https://apifox.com)', 'HTTP_ACCEPT': '*/*', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x000001917DD15D80>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='gbk'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>}, 'request_COOKIES_items': dict_items([]), 'user_str': 'AnonymousUser', 'filtered_POST_items': [], 'settings': {'ABSOLUTE_URL_OVERRIDES': {}, 'ADMINS': [], 'ALLOWED_HOSTS': [], 'APPEND_SLASH': True, 'AUTHENTICATION_BACKENDS': '********************', 'AUTH_PASSWORD_VALIDATORS': '********************', 'AUTH_USER_MODEL': '********************', 'BASE_DIR': WindowsPath('E:/项目/个人博客开发/backend/BlogSystem'), 'CACHES': {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}, 'CACHE_EXPIRY_HOURS': 1, 'CACHE_MIDDLEWARE_ALIAS': 'default', 'CACHE_MIDDLEWARE_KEY_PREFIX': '********************', 'CACHE_MIDDLEWARE_SECONDS': 600, 'CELERY_BEAT_SCHEDULE': {'reset-weather-quota': {'task': 'informa.tasks.reset_monthly_quota', 'schedule': <crontab: 0 0 1 * * (m/h/dM/MY/d)>}, 'update-weather-cache': {'task': 'informa.tasks.update_weather_caches', 'schedule': <crontab: */30 * * * * (m/h/dM/MY/d)>}, 'clean-deleted-media': {'task': 'informa.management.commands.clean_deleted_media.Command.handle', 'schedule': <crontab: 0 0 1 * * (m/h/dM/MY/d)>}}, 'CELERY_BROKER_URL': 'redis://localhost:6379/0', 'CELERY_RESULT_BACKEND': 'redis://localhost:6379/0', 'CELERY_TIMEZONE': 'Asia/Shanghai', 'CORS_ALLOWED_ORIGINS': ['http://localhost:5173'], 'CORS_ALLOW_CREDENTIALS': True, 'CORS_ALLOW_HEADERS': ['authorization', 'content-type'], 'CORS_ALLOW_METHODS': ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'], 'CSRF_COOKIE_AGE': 31449600, 'CSRF_COOKIE_DOMAIN': None, 'CSRF_COOKIE_HTTPONLY': False, 'CSRF_COOKIE_NAME': 'csrftoken', 'CSRF_COOKIE_PATH': '/', 'CSRF_COOKIE_SAMESITE': 'Lax', 'CSRF_COOKIE_SECURE': False, 'CSRF_FAILURE_VIEW': 'django.views.csrf.csrf_failure', 'CSRF_HEADER_NAME': 'HTTP_X_CSRFTOKEN', 'CSRF_TRUSTED_ORIGINS': [], 'CSRF_USE_SESSIONS': False, 'DATABASES': {'default': {'ENGINE': 'django.db.backends.postgresql', 'NAME': 'blogsystem', 'USER': 'postgres', 'PASSWORD': '********************', 'HOST': '127.0.0.1', 'PORT': '5432', 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'CONN_HEALTH_CHECKS': False, 'OPTIONS': {}, 'TIME_ZONE': None, 'TEST': {'CHARSET': None, 'COLLATION': None, 'MIGRATE': True, 'MIRROR': None, 'NAME': None}}}, 'DATABASE_ROUTERS': [], 'DATA_UPLOAD_MAX_MEMORY_SIZE': 2621440, 'DATA_UPLOAD_MAX_NUMBER_FIELDS': 1000, 'DATA_UPLOAD_MAX_NUMBER_FILES': 100, 'DATETIME_FORMAT': 'N j, Y, P', 'DATETIME_INPUT_FORMATS': ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M'], 'DATE_FORMAT': 'N j, Y', 'DATE_INPUT_FORMATS': ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y'], 'DEBUG': True, 'DEBUG_PROPAGATE_EXCEPTIONS': False, 'DECIMAL_SEPARATOR': '.', 'DEFAULT_AUTO_FIELD': 'django.db.models.BigAutoField', 'DEFAULT_CHARSET': 'utf-8', 'DEFAULT_EXCEPTION_REPORTER': 'django.views.debug.ExceptionReporter', 'DEFAULT_EXCEPTION_REPORTER_FILTER': 'django.views.debug.SafeExceptionReporterFilter', 'DEFAULT_FROM_EMAIL': 'webmaster@localhost', 'DEFAULT_INDEX_TABLESPACE': '', 'DEFAULT_TABLESPACE': '', 'DISALLOWED_USER_AGENTS': [], 'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend', 'EMAIL_HOST': 'localhost', 'EMAIL_HOST_PASSWORD': '********************', 'EMAIL_HOST_USER': '', 'EMAIL_PORT': 25, 'EMAIL_SSL_CERTFILE': None, 'EMAIL_SSL_KEYFILE': '********************', 'EMAIL_SUBJECT_PREFIX': '[Django] ', 'EMAIL_TIMEOUT': None, 'EMAIL_USE_LOCALTIME': False, 'EMAIL_USE_SSL': False, 'EMAIL_USE_TLS': False, 'FILE_UPLOAD_DIRECTORY_PERMISSIONS': None, 'FILE_UPLOAD_HANDLERS': ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler'], 'FILE_UPLOAD_MAX_MEMORY_SIZE': 2621440, 'FILE_UPLOAD_PERMISSIONS': 420, 'FILE_UPLOAD_TEMP_DIR': None, 'FIRST_DAY_OF_WEEK': 0, 'FIXTURE_DIRS': [], 'FORCE_SCRIPT_NAME': None, 'FORMAT_MODULE_PATH': None, 'FORMS_URLFIELD_ASSUME_HTTPS': False, 'FORM_RENDERER': 'django.forms.renderers.DjangoTemplates', 'IGNORABLE_404_URLS': [], 'INSTALLED_APPS': ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'rest_framework_simplejwt', 'corsheaders', 'rest_framework', 'django_filters', 'acticles', 'system', 'informa'], 'INTERNAL_IPS': [], 'LANGUAGES': [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokm\xe5l'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], 'LANGUAGES_BIDI': ['he', 'ar', 'ar-dz', 'ckb', 'fa', 'ug', 'ur'], 'LANGUAGE_CODE': 'zh-hans', 'LANGUAGE_COOKIE_AGE': None, 'LANGUAGE_COOKIE_DOMAIN': None, 'LANGUAGE_COOKIE_HTTPONLY': False, 'LANGUAGE_COOKIE_NAME': 'django_language', 'LANGUAGE_COOKIE_PATH': '/', 'LANGUAGE_COOKIE_SAMESITE': None, 'LANGUAGE_COOKIE_SECURE': False, 'LOCALE_PATHS': [], 'LOGGING': {'version': 1, 'disable_existing_loggers': False, 'handlers': {'file': {'level': 'DEBUG', 'class': 'logging.FileHandler', 'filename': 'E:\\项目\\个人博客开发\\backend\\BlogSystem\\debug.log'}}, 'loggers': {'django': {'handlers': ['file'], 'level': 'DEBUG', 'propagate': True}, 'celery': {'handlers': ['file'], 'level': 'DEBUG', 'propagate': True}}}, 'LOGGING_CONFIG': 'logging.config.dictConfig', 'LOGIN_REDIRECT_URL': '/accounts/profile/', 'LOGIN_URL': '/accounts/login/', 'LOGOUT_REDIRECT_URL': None, 'MANAGERS': [], 'MEDIA_ROOT': 'E:\\项目\\个人博客开发\\backend\\BlogSystem\\media', 'MEDIA_URL': '/media/', 'MESSAGE_STORAGE': 'django.contrib.messages.storage.fallback.FallbackStorage', 'MIDDLEWARE': ['corsheaders.middleware.CorsMiddleware', 'django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware'], 'MIGRATION_MODULES': {}, 'MONITORED_LOCATIONS': ['Beijing', 'Shanghai', 'New York', 'WuHan'], 'MONTH_DAY_FORMAT': 'F j', 'NUMBER_GROUPING': 0, 'PASSWORD_HASHERS': '********************', 'PASSWORD_RESET_TIMEOUT': '********************', 'PREPEND_WWW': False, 'REST_FRAMEWORK': {'DEFAULT_AUTHENTICATION_CLASSES': '********************', 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',)}, 'ROOT_URLCONF': 'BlogSystem.urls', 'SECRET_KEY': '********************', 'SECRET_KEY_FALLBACKS': '********************', 'SECURE_CONTENT_TYPE_NOSNIFF': True, 'SECURE_CROSS_ORIGIN_OPENER_POLICY': 'same-origin', 'SECURE_HSTS_INCLUDE_SUBDOMAINS': False, 'SECURE_HSTS_PRELOAD': False, 'SECURE_HSTS_SECONDS': 0, 'SECURE_PROXY_SSL_HEADER': None, 'SECURE_REDIRECT_EXEMPT': [], 'SECURE_REFERRER_POLICY': 'same-origin', 'SECURE_SSL_HOST': None, 'SECURE_SSL_REDIRECT': False, 'SERVER_EMAIL': 'root@localhost', 'SESSION_CACHE_ALIAS': 'default', 'SESSION_COOKIE_AGE': 1209600, 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_NAME': 'sessionid', 'SESSION_COOKIE_PATH': '/', 'SESSION_COOKIE_SAMESITE': 'Lax', 'SESSION_COOKIE_SECURE': False, 'SESSION_ENGINE': 'django.contrib.sessions.backends.db', 'SESSION_EXPIRE_AT_BROWSER_CLOSE': False, 'SESSION_FILE_PATH': None, 'SESSION_SAVE_EVERY_REQUEST': False, 'SESSION_SERIALIZER': 'django.contrib.sessions.serializers.JSONSerializer', 'SETTINGS_MODULE': 'BlogSystem.settings', 'SHORT_DATETIME_FORMAT': 'm/d/Y P', 'SHORT_DATE_FORMAT': 'm/d/Y', 'SIGNING_BACKEND': 'django.core.signing.TimestampSigner', 'SILENCED_SYSTEM_CHECKS': [], 'SIMPLE_JWT': {'ACCESS_TOKEN_LIFETIME': '********************', 'REFRESH_TOKEN_LIFETIME': '********************', 'ROTATE_REFRESH_TOKENS': '********************', 'BLACKLIST_AFTER_ROTATION': True, 'UPDATE_LAST_LOGIN': True, 'ALGORITHM': 'HS256', 'SIGNING_KEY': '********************', 'VERIFYING_KEY': '********************', 'AUDIENCE': None, 'ISSUER': None, 'AUTH_HEADER_TYPES': '********************', 'USER_ID_FIELD': 'id', 'USER_ID_CLAIM': 'user_id', 'USER_AUTHENTICATION_RULE': '********************', 'AUTH_TOKEN_CLASSES': '********************', 'TOKEN_TYPE_CLAIM': '********************'}, 'STATICFILES_DIRS': [], 'STATICFILES_FINDERS': ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder'], 'STATIC_ROOT': None, 'STATIC_URL': '/static/', 'STORAGES': {'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'}, 'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'}}, 'TEMPLATES': [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}], 'TEST_NON_SERIALIZED_APPS': [], 'TEST_RUNNER': 'django.test.runner.DiscoverRunner', 'THOUSAND_SEPARATOR': ',', 'TIME_FORMAT': 'P', 'TIME_INPUT_FORMATS': ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M'], 'TIME_ZONE': 'UTC', 'USE_I18N': True, 'USE_THOUSAND_SEPARATOR': False, 'USE_TZ': True, 'USE_X_FORWARDED_HOST': False, 'USE_X_FORWARDED_PORT': False, 'WEATHER_API_HOST': '********************', 'WEATHER_API_KEY': '********************', 'WEATHER_API_URL': '********************', 'WSGI_APPLICATION': 'BlogSystem.wsgi.application', 'X_FRAME_OPTIONS': 'DENY', 'YEAR_MONTH_FORMAT': 'F Y'}, 'sys_executable': 'E:\\项目\\个人博客开发\\backend\\.venv\\Scripts\\python.exe', 'sys_version_info': '3.12.7', 'server_time': datetime.datetime(2025, 7, 17, 8, 31, 46, 383427, tzinfo=datetime.timezone.utc), 'django_version_info': '5.2.4', 'sys_path': ['E:\\项目\\个人博客开发\\backend\\BlogSystem', 'E:\\项目\\个人博客开发\\backend\\BlogSystem', 'D:\\Software\\anaconda3\\python312.zip', 'D:\\Software\\anaconda3\\DLLs', 'D:\\Software\\anaconda3\\Lib', 'D:\\Software\\anaconda3', 'E:\\项目\\个人博客开发\\backend\\.venv', 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages', 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\setuptools\\_vendor'], 'template_info': None, 'template_does_not_exist': False, 'postmortem': None, 'request_GET_items': <generator object MultiValueDict.items at 0x000001917DD35150>, 'request_FILES_items': <generator object MultiValueDict.items at 0x000001917DD37780>, 'request_insecure_uri': 'http://127.0.0.1:8000/api/articles', 'raising_view_name': '', 'exception_type': 'RuntimeError', 'exception_value': "You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/articles/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.", 'lastframe': {'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x000001917DD26640>, 'type': 'django', 'filename': 'E:\\项目\\个人博客开发\\backend\\.venv\\Lib\\site-packages\\django\\middleware\\common.py', 'function': 'get_full_path_with_slash', 'lineno': 87, 'vars': [('self', '<CommonMiddleware get_response=convert_exception_to_response.<locals>.inner>'), ('request', "<WSGIRequest: POST '/api/articles'>"), ('new_path', "'/api/articles/'")], 'id': 1724392826432, 'pre_context': ['        Raise a RuntimeError if settings.DEBUG is True and request.method is', '        DELETE, POST, PUT, or PATCH.', '        """', '        new_path = request.get_full_path(force_append_slash=True)', '        # Prevent construction of scheme relative urls.', '        new_path = escape_leading_slashes(new_path)', '        if settings.DEBUG and request.method in ("DELETE", "POST", "PUT", "PATCH"):'], 'context_line': '            raise RuntimeError(', 'post_context': ['                "You called this URL via %(method)s, but the URL doesn\'t end "', '                "in a slash and you have APPEND_SLASH set. Django can\'t "', '                "redirect to the slash URL while maintaining %(method)s data. "', '                "Change your form to point to %(url)s (note the trailing "', '                "slash), or set APPEND_SLASH=False in your Django settings."', '                % {'], 'pre_context_lineno': 80, 'colno': '\n                ^', 'tb_area_colno': '\n    ^'}}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\anaconda3\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\xe5' in position 20788: illegal multibyte sequence
Call stack:
  File "D:\Software\anaconda3\Lib\threading.py", line 1032, in _bootstrap
    self._bootstrap_inner()
  File "D:\Software\anaconda3\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "D:\Software\anaconda3\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Software\anaconda3\Lib\socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\Software\anaconda3\Lib\socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Software\anaconda3\Lib\socketserver.py", line 761, in __init__
    self.handle()
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\servers\basehttp.py", line 230, in handle
    self.handle_one_request()
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\servers\basehttp.py", line 253, in handle_one_request
    handler.run(self.server.get_app())
  File "D:\Software\anaconda3\Lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\contrib\staticfiles\handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\corsheaders\middleware.py", line 56, in __call__
    result = self.get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\utils\deprecation.py", line 120, in __call__
    response = response or self.get_response(request)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 182, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\views\debug.py", line 429, in get_traceback_html
    return t.render(c)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 320, in render
    match = condition.eval(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "E:\项目\个人博客开发\backend\.venv\Lib\site-packages\django\template\base.py", line 941, in _resolve_lookup
    logger.debug(
Message: "Exception while resolving variable '%s' in template '%s'."
Arguments: ('exception_notes', 'unknown')
